version: '3'
services:
  mysql:
    image: mysql:5.7
    env_file: .env
  osticket:
    build: .
    image: digitalorganic/osticket:latest
    env_file: .env
    ports:
      - 8080:80
    restart: on-failure
