version: '3'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: osticket
      MYSQL_USER: osticket
      MYSQL_PASSWORD: secret
      INSTALL_SECRET: b869cee4ce4b003fd389992cf1cf1c722797e4b9557e88bdcf60377688a0efb0
      INSTALL_EMAIL: support@do.co.th
      INSTALL_URL: http://localhost:8080
      INSTALL_NAME: DO Support
      ADMIN_FIRSTNAME: Songpon
      ADMIN_LASTNAME: Phusing
      ADMIN_EMAIL: songpon.p@do.co.th
      ADMIN_USERNAME: songpon
      ADMIN_PASSWORD: bla0bla00
  osticket:
    build: .
    image: digitalorganic/osticket:latest
    environment:
      MYSQL_HOST: mysql
      MYSQL_DATABASE: osticket
      MYSQL_USER: osticket
      MYSQL_PASSWORD: secret
    ports:
      - 8080:80
    restart: on-failure
